---
destroy: false
lab_default_image: rhel-8.7-x86_64-kvm.qcow2
vmpass: redhat

public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC34tubkhNNbaw6KVh4CwgKI3LJKh93DE8lxrxXa4nf1tAQTeMW0gd2mj6zp0jHMExjZT+2iAz9YB93JfiLoHHqQzxzFj6wJkS2hyuZZ46j/K/tjejivrNNs02U0uUKKwWmoZLK7zdALn+hzlQ95IgRctMQ9OFWNwF9lXoMJzd8iv6Io7jcusCjuKRuxPbDMxDDQN9Ij5RfjsbFxymVUjHcJ6a/ejJmqCu7gdXZvzxEI2tlGV1vW+wpxIEAgwrAn0N0sNjTAQNwCv8dJDo2AAbdWZPfSysF64GbIk63Nk7A0aHO0NfI1M6jLS/TxKaTDtQIAH3G+Exln80T+MoWgYqPTxQsd35n0k5YnvWnpgtKstRrOVHVbZUq/yW/cqw0hKPOQkElw+wjJXwHaqEnMX7LPlIvaUq+k2tUkEN2uTS1NyOOypx2iBvvsmJAn2ajmo2MsGBVc3sOeQ99fehcAuVgyQJm8BgVHGohWCqdlbIZNa8E0hig2h97n8bP6XzYUvU= root@CentOS-80-stream-amd64-base"
